ALTER TABLE "CleaningTask" ADD COLUMN IF NOT EXISTS "cullaRequested" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CleaningTask" ADD COLUMN IF NOT EXISTS "sofaBedForced" BOOLEAN NOT NULL DEFAULT false;
