ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "conflictMaxCleaningsPerDay" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "conflictUrgentHours" INTEGER NOT NULL DEFAULT 48;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "conflictStaleTicketDays" INTEGER NOT NULL DEFAULT 7;
ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS "conflictOverlapMinutes" INTEGER NOT NULL DEFAULT 90;
